spring.datasource.url=jdbc:postgresql://${DATABASE_URI:vector-database}/${DATABASE_NAME:vector_db}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=32

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:public}
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.properties.hibernate.packagesToScan="ru.skoltech.aeronetlab.markupstorage"
entitymanager.packagesToScan: ru.skoltech.aeronetlab.markupstorage

spring.jackson.mapper.default-view-inclusion=true

spring.http.multipart.max-file-size=200GB
spring.http.multipart.max-request-size=200GB
spring.servlet.multipart.max-file-size=200GB
spring.servlet.multipart.max-request-size=200GB

spring.mvc.async.request-timeout=8h

spring.jpa.properties.hibernate.jdbc.batch_size=10000

spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.   simple.max-concurrency=1

logging.level.ru.skoltech=${LOGGING_LEVEL:INFO}

spring.jpa.show-sql=${SHOW_SQL:false}
logging.level.org.hibernate.SQL=${SQL_LOG_LEVEL:INFO}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${SQL_LOG_LEVEL:INFO}
logging.level.org.flywaydb=${SQL_LOG_LEVEL:INFO}

spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://${DATABASE_URI:vector-database}/${DATABASE_NAME:vector_db}
spring.flyway.password=}
spring.flyway.user=${DATABASE_USER:postgres}
spring.flyway.schemas=${DATABASE_SCHEMA:public}
spring.flyway.table=${FLYWAY_TABLE:schema_history}

spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.direct.prefetch=1
