import os
import json
import base64
from pathlib import Path
from loguru import logger
from typing import Sequence, Optional, Dict
from tempfile import TemporaryDirectory
from shapely.geometry.base import BaseGeometry
from pydantic import ValidationError

import urban

from .storage import InferenceStorage
from .message import InferenceArtifact
from .errors import ConfigValidationError


class DataProcessor:

    def __init__(
        self,
        pipeline: str,  # base64 encoded pipeline
        input_artifacts: Sequence[InferenceArtifact],
        output_artifacts: Sequence[InferenceArtifact],
        storage: InferenceStorage,  # s3_resource; no type hint because boto3 is bad at it
        aoi: BaseGeometry,
        enable_blocks: Optional[Dict[str, bool]] = None
    ):
        self.storage = storage
        self.input_artifacts = input_artifacts
        self.output_artifacts = output_artifacts
        self.pipeline = pipeline
        self.aoi = aoi
        self.workdir = Path()
        self.enable_blocks = enable_blocks
    
    def make_pipeline(self):
        logger.trace(f"Base64 pipeline: {self.pipeline}")
        pipeline_path = self.workdir/"pipeline.yaml"
        with open(pipeline_path, "wb") as f:
            bytes = base64.b64decode(self.pipeline)
            logger.trace(bytes.decode("utf-8"))
            f.write(bytes)
        pipeline = urban.Compose.load(pipeline_path, enable_blocks=self.enable_blocks)
        logger.debug("Pipeline loaded: {}".format(json.dumps(pipeline.get_config(), indent=2)))
        return pipeline

    def run(self,
            task_id: Optional[str] = None,
            processing_id: Optional[str] = None,
            bucket: Optional[str] = None):
        with TemporaryDirectory() as workdir_name:
            os.environ['PROCESSING_ID'] = processing_id
            try:
                pipeline = self.make_pipeline()
            except ValidationError as e:
                raise ConfigValidationError.from_pydantic_error(e)
            self.workdir = Path(workdir_name)
            for artifact in self.input_artifacts:
                self.storage.get_artifact(artifact=artifact,
                                          workdir=self.workdir,
                                          aoi=self.aoi)

            outputs = pipeline(self.workdir)

            for artifact in self.output_artifacts:
                logger.debug(f"Uploading {artifact.name} to {artifact.path}")
                self.storage.upload(workdir=self.workdir, artifact=artifact)

            # these are outputs that are generated by pipeline, but not listed in output_artifacts
            # The worker generates the output path and uploads them
            # This allows to define the outputs in the pipelines and upload them, without WE knowing about them
            if task_id and processing_id and bucket:
                arbitrary_outputs = (file for file in outputs
                                     if file not in (artifact.name for artifact in self.output_artifacts))
                for file in arbitrary_outputs:
                    artifact = InferenceArtifact(name=file,
                                                 path=f"s3://{bucket}/processing-{processing_id}/task-{task_id}-{file}")
                    # Uploading arbitrary outputs to the /processing-<processing_id> directory in the same bucket
                    logger.debug(f"Uploading arbitrary output {file} to {artifact.path}")
                    self.storage.upload(workdir=self.workdir, artifact=artifact)


