spring.datasource.url=jdbc:postgresql://${DATABASE_URI:localhost}/${DATABASE_NAME:engine_db}?currentSchema=${DATABASE_SCHEMA:public}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=}

spring.jpa.generate-ddl=false
spring.flyway.baseline-version=001.0

spring.flyway.default-schema=${DATABASE_SCHEMA:public}
# TODO: Remove this property after rolling initial release to all environments
spring.flyway.baseline-on-migrate=true
spring.jpa.show-sql=${SHOW_SQL:false}

spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

spring.jpa.properties.hibernate.packagesToScan="ru.skoltech.aeronetlab.urban.model"
spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:public}

# Disable feature detection since it produces exception during start
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

# serialize dates to JSON as "2017-12-05", not as array [2017,12,05]
spring.jackson.serialization.write_dates_as_timestamps=false

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.max-http-header-size=1024KB


spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:25}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.listener.simple.prefetch=16
spring.rabbitmq.listener.direct.prefetch=16

logging.level.ru.skoltech.aeronetlab.urban=${LOG_LEVEL:INFO}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

springdoc.packagesToScan=ru.skoltech.aeronetlab.urban.api
springdoc.pathsToMatch=/api/v0/**