spring.datasource.url=jdbc:postgresql://database:5432/markup_storage_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.properties.hibernate.packagesToScan="ru.skoltech.aeronetlab.markupstorage"
entitymanager.packagesToScan: ru.skoltech.aeronetlab.markupstorage

spring.jackson.mapper.default-view-inclusion=true

spring.http.multipart.max-file-size=1000MB
spring.http.multipart.max-request-size=1000MB

spring.jpa.properties.hibernate.jdbc.batch_size=10000


#spring.jpa.show-sql=true