ALTER TABLE app_user ADD COLUMN IF NOT EXISTS name VARCHAR(64);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS preferred_username VARCHAR(64);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS avantpost_user_id UUID;