ALTER TABLE workflow ADD COLUMN IF NOT EXISTS "locked" BOOLEAN DEFAULT FALSE;
ALTER TABLE workflow ADD COLUMN IF NOT EXISTS "locked_at" TIMESTAMP;
ALTER TABLE workflow ADD COLUMN IF NOT EXISTS "failed_count" INT DEFAULT 0;