from .simplification import simplify_fc_with_shapes
from . import aligning
from . import constants
from . import topology
from . import filters
from . import merge
from . import smooth
from . import difference
from . import instance_separation
from . import flatten_multipolygons
from . import network
from . import dissolve
from . import linestrings
from . import merge_close_objects
