"""add footprint column

Revision ID: 2aca6a6de019
Revises: 4c42a1f44d64
Create Date: 2022-06-28 23:54:51.841653

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aca6a6de019'
down_revision = '4c42a1f44d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('footprint',
                                      geoalchemy2.types.Geometry(geometry_type='POLYGON',
                                                                 from_text='ST_GeomFromEWKT',
                                                                 name='geometry'),
                                      nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'footprint')
    # ### end Alembic commands ###
