"""Add meta data, filename, checksum, file size to images table

Revision ID: 42ad8967260b
Revises: b603161c096c
Create Date: 2022-08-02 00:13:21.480495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42ad8967260b'
down_revision = 'b603161c096c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('images', sa.Column('checksum', sa.String(), nullable=True))
    op.add_column('images', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('images', sa.Column('file_size', sa.Integer(), nullable=True))
    op.drop_column('mosaics', 'shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mosaics', sa.Column('shared', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('images', 'file_size')
    op.drop_column('images', 'meta_data')
    op.drop_column('images', 'checksum')
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
