"""initial migration: creating tables: users, images, mosaics, usermosaic

Revision ID: 4c42a1f44d64
Revises: 
Create Date: 2022-06-28 23:47:45.269352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c42a1f44d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mosaics',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('owner_id', postgresql.UUID(), nullable=True),
                    sa.Column('raster_layer', sa.String(), nullable=True),
                    sa.Column('tilejson_url', sa.String(), nullable=True),
                    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('users',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('login', sa.String(), nullable=True),
                    sa.Column('memory_used', sa.Integer(), nullable=True),
                    sa.Column('memory_limit', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('images',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('mosaic_id', postgresql.UUID(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('preview_url', sa.String(), nullable=True),
                    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['mosaic_id'], ['mosaics.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('usermosaic',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=True),
                    sa.Column('mosaic_id', postgresql.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['mosaic_id'], ['mosaics.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermosaic')
    op.drop_table('images')
    op.drop_table('users')
    op.drop_table('mosaics')
    # ### end Alembic commands ###
