"""add names created_at columns to mosaics table

Revision ID: 5c4db9ad27d2
Revises: c3ddf139858c
Create Date: 2022-11-07 13:07:33.578200

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4db9ad27d2'
down_revision = 'c3ddf139858c'
# branch_labels = None
# depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mosaics', sa.Column('name', sa.String(), nullable=True))
    op.add_column('mosaics', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))

    conn = op.get_bind()
    # fill mosaics.name column with mosaics.id values
    conn.execute("update mosaics set name = id")

    # fill mosaic.created_at with MIN(images.uploaded_at) where images.mosaic_id == mosaics.id or
    # datetime.now() if no image exists
    results = conn.execute("select m.id, i.mosaic_id, MIN(i.uploaded_at) \
    from mosaics m \
    left join images i on m.id = i.mosaic_id \
    group by m.id, i.mosaic_id;")

    for r in results:
        mosaic_id = r[0]
        if r[2]:
            created_at = r[2]
        else:
            created_at = datetime.now()
        conn.execute(f"update mosaics set created_at = '{str(created_at)}' where id = '{mosaic_id}';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mosaics', 'created_at')
    op.drop_column('mosaics', 'name')
    # ### end Alembic commands ###
