"""update mosaics table

Revision ID: 9102b00bea8d
Revises: 2aca6a6de019
Create Date: 2022-07-07 12:39:55.125287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9102b00bea8d'
down_revision = '2aca6a6de019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mosaics', sa.Column('mosaic_url', sa.String(), nullable=True))
    op.drop_column('mosaics', 'tilejson_url')
    op.drop_column('mosaics', 'raster_layer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mosaics', sa.Column('raster_layer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mosaics', sa.Column('tilejson_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mosaics', 'mosaic_url')
    # ### end Alembic commands ###
