"""Add shared column to mosaics table

Revision ID: b603161c096c
Revises: 9102b00bea8d
Create Date: 2022-07-26 18:26:55.123171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b603161c096c'
down_revision = '9102b00bea8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_images_footprint', 'images', ['footprint'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('mosaics', sa.Column('shared', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mosaics', 'shared')
    # op.drop_index('idx_images_footprint', table_name='images', postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
