akka.http.client.parsing.max-content-length = 64g
akka.http.server.parsing.max-content-length = 64g
akka.http.parsing.max-to-strict-bytes = 64g
akka.http.parsing.max-content-length = 64g

akka.http.server.idle-timeout = 60.minutes
akka.http.client.idle-timeout = 5.minutes
akka.http.client.connecting-timeout = 10.seconds

akka.http.host-connection-pool.response-entity-subscription-timeout = 4.seconds
akka.http.host-connection-pool.max-open-requests = 128