FROM registry.gitlab.com/geoalert-projects/geoalert-docker/ubuntu-gdal-libspatialindex:0438e6fd

WORKDIR /code

COPY ./tests/test-requirements.txt /code/tests/test-requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/tests/test-requirements.txt
RUN pip install pytest

COPY . /code
ENV PYTHONPATH "${PYTHONPATH}:/code/app/"

WORKDIR /code